export const DATA_FETCH_SUCCESS = "APP/DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILURE = "APP/DATA_FETCH_FAILURE";
export const DATA_FILTERED = "APP/DATA_FILTERED";

export const SET_COMPLETED = "FILTER/SET_COMPLETED";
export const SET_COURSE = "FILTER/SET_COURSE";
export const SET_EVENT = "FILTER/SET_EVENT";
